service: music-history-lambda

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 15

functions:
  scheduler:
    handler: scheduler/handler.schedulerHandler
    events:
      - http:
          private: true
          path: scheduler
          method: post
  music_history:
    handler: music_history/handler.musicHistoryHandler
    events:
      - http:
          private: true
          path: music_history
          method: post
